// <auto-generated />
namespace Assignment3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vote_removestatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vote_removestatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201812150213477_vote_removestatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
